# Generated by Django 5.1 on 2024-09-04 09:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('amount_to_receive', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('payment_method', models.CharField(choices=[('ONLINE', 'Online'), ('COD', 'Cash on Delivery')], max_length=255)),
                ('delivery_status', models.CharField(blank=True, choices=[('PRODUCT_DISPATCHED', 'Product Dispatched'), ('PRODUCT_DELIVERED', 'Product Delivered'), ('ON_ROUTE', 'On Route'), ('UNKNOWN', 'Unknown'), ('CANCELLED', 'Cancelled'), ('RECEIVER_FAILED', 'Receiver Failed')], max_length=255, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_secondary_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('delivery_address', models.TextField()),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_state', models.CharField(max_length=100)),
                ('delivery_zip_code', models.CharField(max_length=20)),
                ('expected_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_person', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_person_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('delivery_instructions', models.TextField(blank=True, null=True)),
                ('order_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
